server:
  port: 9999

spring:
  main:
    web-application-type: reactive
  application:
    name: cloud-gateway-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      discovery:
        locator:
          enabled: false # 默认为false, 开启注册中心路由功能, 把网关服务注册到naocs中(设置为true后, 网关服务会自动到注册中心获取其他注册的服务名 实现负载均衡的功能)
      routes:
        # 路由1
        - id: nacos-provider
          uri: lb://nacos-provider # 通过lb原则手动配置负载均衡 lb://服务名称
          predicates:
            - Path=/gateway/** # 断言, 路径相匹配则进行路由, 访问http://localhost:9001/nacos-provider/gateway/** 时匹配
          filters:
            - StripPrefix=1 # 去掉请求地址中的第一部分, 如http://localhost:9999/gateway/nacos-provider/gateway, 去掉/gateway

        # 路由2
        - id: nacos-provider2
          uri: lb://nacos-provider # 匹配提供服务的路由地址
          predicates:
            - Path=/route/** # 断言, 路径相匹配则进行路由
            - Query=id, .+ # 匹配请求参数, 这里如果需要匹配多个参数, 可以写多个Query断言
            - Query=name, .+ # 请求中必须包含id, name参数 否则还是不路由 返回404
